[package]
name = "filebroker-server"
version = "0.5.0"
authors = ["robinfriedli <robinfriedli@icloud.com>"]
edition = "2021"

[features]
default = []
auto_migration = ["diesel_migrations"]

[dependencies]
async-trait = "0.1.56"
bcrypt = "0.14.0"
bytes = "1.2.0"
chrono = { version = "0.4.19", features = ["serde"] }
clokwerk = "0.4.0"
data-encoding = "2.3.2"
diesel = { version = "2.0.0", features = ["chrono", "postgres", "r2d2", "uuid"] }
diesel-async = { version = "0.3.1", features = ["postgres", "deadpool"] }
dotenvy = "0.15.7"
downcast-rs = "1.2.0"
exec-rs = "0.1.2"
fern = { version = "0.6.1", features = ["date-based"] }
flurry = "0.4.0"
futures = "0.3.21"
governor = "0.5.1"
iso8601 = "0.6.1"
itertools = "0.10.3"
jsonwebtoken = "8.1.0"
lazy_static = "1.4.0"
lettre = { version = "0.10", features = ["dkim"] }
log = "0.4.17"
mime = "0.3.16"
mime_guess = "2.0.4"
mpart-async = "0.6.0"
num_cpus = "1.15.0"
parking_lot = "0.12.1"
passwords = "3.1.13"
percent-encoding = "2.2.0"
pg_interval = "0.4.1"
pin-project-lite = "0.2.9"
rand = "0.8.5"
regex = "1.6.0"
reqwest = { version = "0.11", features = ["json"] }
ring = "0.16.20"
rust-s3 = "0.32.1"
rustls = "0.21.5"
rustls-native-certs = "0.6.3"
rustls-pemfile = "1.0.2"
rusty_pool = "0.7.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tera = "1.19.0"
thiserror = "1.0.24"
tls-listener = { version = "0.7.0", features = ["rustls", "hyper-h1", "hyper-h2"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.8"
tokio-postgres-rustls = "0.10.0"
tokio-rustls = "0.24.1"
url = "2.3.1"
uuid = { version = "1.2.1", features = ["v4", "serde"] }
validator = { version = "0.16.0", features = ["derive"] }
warp = { version = "0.3", features = ["tls"] }
webp = "0.2.2"
zxcvbn = "2.2.2"

[dependencies.diesel_migrations]
version = "2.0.0"
optional = true

[target.'cfg(unix)'.dependencies]
nix = "0.26.2"
tempfile = "3.4.0"
