x-env-files: &env-files
  - path: ./.env
    required: false
  - path: ./.env.secret
    required: false
  - path: ./.env.local
    required: false

services:
  filebroker-server-castor:
    image: ghcr.io/filebroker/filebroker-server:latest
    restart: unless-stopped

    env_file: *env-files

  filebroker-server-pollux:
    image: ghcr.io/filebroker/filebroker-server:latest
    restart: unless-stopped

    env_file: *env-files

  nginx:
    image: ghcr.io/filebroker/filebroker-client:latest
    restart: unless-stopped

    env_file: *env-files

    environment:
      FILEBROKER_API_UPSTREAMS: >-
        server filebroker-server-castor:8080 resolve;
        server filebroker-server-pollux:8080 resolve;

    depends_on:
      - filebroker-server-castor
      - filebroker-server-pollux

    ports:
      - "127.0.0.1:8080:80"

    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - thumb-cache:/data/nginx/thumb_cache

volumes:
  thumb-cache:
