DROP INDEX s3_object_metadata_track_number_idx;
DROP INDEX s3_object_metadata_track_number_desc_idx;

DROP INDEX s3_object_metadata_artist_track_number_idx;
DROP INDEX s3_object_metadata_artist_desc_track_number_idx;
DROP INDEX s3_object_metadata_artist_track_number_desc_idx;
DROP INDEX s3_object_metadata_artist_desc_track_number_desc_idx;
DROP INDEX s3_object_metadata_track_number_artist_idx;
DROP INDEX s3_object_metadata_track_number_artist_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_artist_idx;
DROP INDEX s3_object_metadata_track_number_desc_artist_desc_idx;
DROP INDEX s3_object_metadata_album_track_number_idx;
DROP INDEX s3_object_metadata_album_desc_track_number_idx;
DROP INDEX s3_object_metadata_album_track_number_desc_idx;
DROP INDEX s3_object_metadata_album_desc_track_number_desc_idx;
DROP INDEX s3_object_metadata_track_number_album_idx;
DROP INDEX s3_object_metadata_track_number_album_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_album_idx;
DROP INDEX s3_object_metadata_track_number_desc_album_desc_idx;
DROP INDEX s3_object_metadata_date_track_number_idx;
DROP INDEX s3_object_metadata_date_desc_track_number_idx;
DROP INDEX s3_object_metadata_date_track_number_desc_idx;
DROP INDEX s3_object_metadata_date_desc_track_number_desc_idx;
DROP INDEX s3_object_metadata_track_number_date_idx;
DROP INDEX s3_object_metadata_track_number_date_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_date_idx;
DROP INDEX s3_object_metadata_track_number_desc_date_desc_idx;
DROP INDEX s3_object_metadata_duration_track_number_idx;
DROP INDEX s3_object_metadata_duration_desc_track_number_idx;
DROP INDEX s3_object_metadata_duration_track_number_desc_idx;
DROP INDEX s3_object_metadata_duration_desc_track_number_desc_idx;
DROP INDEX s3_object_metadata_track_number_duration_idx;
DROP INDEX s3_object_metadata_track_number_duration_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_duration_idx;
DROP INDEX s3_object_metadata_track_number_desc_duration_desc_idx;

DROP INDEX s3_object_metadata_track_number_width_idx;
DROP INDEX s3_object_metadata_track_number_desc_width_idx;
DROP INDEX s3_object_metadata_track_number_width_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_width_desc_idx;
DROP INDEX s3_object_metadata_width_track_number_idx;
DROP INDEX s3_object_metadata_width_track_number_desc_idx;
DROP INDEX s3_object_metadata_width_desc_track_number_idx;
DROP INDEX s3_object_metadata_width_desc_track_number_desc_idx;

DROP INDEX s3_object_metadata_track_number_height_idx;
DROP INDEX s3_object_metadata_track_number_desc_height_idx;
DROP INDEX s3_object_metadata_track_number_height_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_height_desc_idx;
DROP INDEX s3_object_metadata_height_track_number_idx;
DROP INDEX s3_object_metadata_height_track_number_desc_idx;
DROP INDEX s3_object_metadata_height_desc_track_number_idx;
DROP INDEX s3_object_metadata_height_desc_track_number_desc_idx;

DROP INDEX s3_object_metadata_track_number_size_idx;
DROP INDEX s3_object_metadata_track_number_desc_size_idx;
DROP INDEX s3_object_metadata_track_number_size_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_size_desc_idx;
DROP INDEX s3_object_metadata_size_track_number_idx;
DROP INDEX s3_object_metadata_size_track_number_desc_idx;
DROP INDEX s3_object_metadata_size_desc_track_number_idx;
DROP INDEX s3_object_metadata_size_desc_track_number_desc_idx;

DROP INDEX s3_object_metadata_disc_number_idx;
DROP INDEX s3_object_metadata_disc_number_desc_idx;

DROP INDEX s3_object_metadata_artist_disc_number_idx;
DROP INDEX s3_object_metadata_artist_desc_disc_number_idx;
DROP INDEX s3_object_metadata_artist_disc_number_desc_idx;
DROP INDEX s3_object_metadata_artist_desc_disc_number_desc_idx;
DROP INDEX s3_object_metadata_disc_number_artist_idx;
DROP INDEX s3_object_metadata_disc_number_artist_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_artist_idx;
DROP INDEX s3_object_metadata_disc_number_desc_artist_desc_idx;
DROP INDEX s3_object_metadata_album_disc_number_idx;
DROP INDEX s3_object_metadata_album_desc_disc_number_idx;
DROP INDEX s3_object_metadata_album_disc_number_desc_idx;
DROP INDEX s3_object_metadata_album_desc_disc_number_desc_idx;
DROP INDEX s3_object_metadata_disc_number_album_idx;
DROP INDEX s3_object_metadata_disc_number_album_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_album_idx;
DROP INDEX s3_object_metadata_disc_number_desc_album_desc_idx;
DROP INDEX s3_object_metadata_date_disc_number_idx;
DROP INDEX s3_object_metadata_date_desc_disc_number_idx;
DROP INDEX s3_object_metadata_date_disc_number_desc_idx;
DROP INDEX s3_object_metadata_date_desc_disc_number_desc_idx;
DROP INDEX s3_object_metadata_disc_number_date_idx;
DROP INDEX s3_object_metadata_disc_number_date_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_date_idx;
DROP INDEX s3_object_metadata_disc_number_desc_date_desc_idx;
DROP INDEX s3_object_metadata_duration_disc_number_idx;
DROP INDEX s3_object_metadata_duration_desc_disc_number_idx;
DROP INDEX s3_object_metadata_duration_disc_number_desc_idx;
DROP INDEX s3_object_metadata_duration_desc_disc_number_desc_idx;
DROP INDEX s3_object_metadata_disc_number_duration_idx;
DROP INDEX s3_object_metadata_disc_number_duration_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_duration_idx;
DROP INDEX s3_object_metadata_disc_number_desc_duration_desc_idx;
DROP INDEX s3_object_metadata_track_number_disc_number_idx;
DROP INDEX s3_object_metadata_track_number_desc_disc_number_idx;
DROP INDEX s3_object_metadata_track_number_disc_number_desc_idx;
DROP INDEX s3_object_metadata_track_number_desc_disc_number_desc_idx;
DROP INDEX s3_object_metadata_disc_number_track_number_idx;
DROP INDEX s3_object_metadata_disc_number_track_number_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_track_number_idx;
DROP INDEX s3_object_metadata_disc_number_desc_track_number_desc_idx;

DROP INDEX s3_object_metadata_disc_number_width_idx;
DROP INDEX s3_object_metadata_disc_number_desc_width_idx;
DROP INDEX s3_object_metadata_disc_number_width_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_width_desc_idx;
DROP INDEX s3_object_metadata_width_disc_number_idx;
DROP INDEX s3_object_metadata_width_disc_number_desc_idx;
DROP INDEX s3_object_metadata_width_desc_disc_number_idx;
DROP INDEX s3_object_metadata_width_desc_disc_number_desc_idx;

DROP INDEX s3_object_metadata_disc_number_height_idx;
DROP INDEX s3_object_metadata_disc_number_desc_height_idx;
DROP INDEX s3_object_metadata_disc_number_height_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_height_desc_idx;
DROP INDEX s3_object_metadata_height_disc_number_idx;
DROP INDEX s3_object_metadata_height_disc_number_desc_idx;
DROP INDEX s3_object_metadata_height_desc_disc_number_idx;
DROP INDEX s3_object_metadata_height_desc_disc_number_desc_idx;

DROP INDEX s3_object_metadata_disc_number_size_idx;
DROP INDEX s3_object_metadata_disc_number_desc_size_idx;
DROP INDEX s3_object_metadata_disc_number_size_desc_idx;
DROP INDEX s3_object_metadata_disc_number_desc_size_desc_idx;
DROP INDEX s3_object_metadata_size_disc_number_idx;
DROP INDEX s3_object_metadata_size_disc_number_desc_idx;
DROP INDEX s3_object_metadata_size_desc_disc_number_idx;
DROP INDEX s3_object_metadata_size_desc_disc_number_desc_idx;

ALTER TABLE s3_object_metadata ALTER COLUMN track_number TYPE TEXT USING track_number::TEXT;
UPDATE s3_object_metadata SET track_number = track_number || '/' || track_count WHERE track_count IS NOT NULL;
ALTER TABLE s3_object_metadata DROP COLUMN track_count;

ALTER TABLE s3_object_metadata ALTER COLUMN disc_number TYPE TEXT USING disc_number::TEXT;
UPDATE s3_object_metadata SET disc_number = disc_number || '/' || disc_count WHERE disc_count IS NOT NULL;
ALTER TABLE s3_object_metadata DROP COLUMN disc_count;

CREATE INDEX s3_object_metadata_track_number_idx ON s3_object_metadata(LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_gin_idx ON s3_object_metadata USING gin(LOWER(track_number) gin_trgm_ops);

CREATE INDEX s3_object_metadata_artist_track_number_idx ON s3_object_metadata(LOWER(artist), LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_artist_desc_track_number_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_artist_track_number_desc_idx ON s3_object_metadata(LOWER(artist), LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_track_number_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_artist_idx ON s3_object_metadata(LOWER(track_number), LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_track_number_artist_desc_idx ON s3_object_metadata(LOWER(track_number), LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_artist_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_artist_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_track_number_idx ON s3_object_metadata(LOWER(album), LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_album_desc_track_number_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_album_track_number_desc_idx ON s3_object_metadata(LOWER(album), LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_track_number_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_album_idx ON s3_object_metadata(LOWER(track_number), LOWER(album), object_key);
CREATE INDEX s3_object_metadata_track_number_album_desc_idx ON s3_object_metadata(LOWER(track_number), LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_album_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_album_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_track_number_idx ON s3_object_metadata(date, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_date_desc_track_number_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_date_track_number_desc_idx ON s3_object_metadata(date, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_track_number_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_date_idx ON s3_object_metadata(LOWER(track_number), date, object_key);
CREATE INDEX s3_object_metadata_track_number_date_desc_idx ON s3_object_metadata(LOWER(track_number), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_date_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_date_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_track_number_idx ON s3_object_metadata(duration, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_duration_desc_track_number_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_duration_track_number_desc_idx ON s3_object_metadata(duration, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_track_number_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_duration_idx ON s3_object_metadata(LOWER(track_number), duration, object_key);
CREATE INDEX s3_object_metadata_track_number_duration_desc_idx ON s3_object_metadata(LOWER(track_number), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_duration_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_duration_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, duration DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_track_number_width_idx ON s3_object_metadata(LOWER(track_number), width, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_width_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_track_number_width_desc_idx ON s3_object_metadata(LOWER(track_number), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_width_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_track_number_idx ON s3_object_metadata(width, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_width_track_number_desc_idx ON s3_object_metadata(width, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_track_number_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_width_desc_track_number_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_track_number_height_idx ON s3_object_metadata(LOWER(track_number), height, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_height_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_track_number_height_desc_idx ON s3_object_metadata(LOWER(track_number), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_height_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_track_number_idx ON s3_object_metadata(height, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_height_track_number_desc_idx ON s3_object_metadata(height, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_track_number_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_height_desc_track_number_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_track_number_size_idx ON s3_object_metadata(LOWER(track_number), size, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_size_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_track_number_size_desc_idx ON s3_object_metadata(LOWER(track_number), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_size_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_track_number_idx ON s3_object_metadata(size, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_size_track_number_desc_idx ON s3_object_metadata(size, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_track_number_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_size_desc_track_number_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_disc_number_idx ON s3_object_metadata(LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_gin_idx ON s3_object_metadata USING gin(LOWER(disc_number) gin_trgm_ops);

CREATE INDEX s3_object_metadata_artist_disc_number_idx ON s3_object_metadata(LOWER(artist), LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_artist_desc_disc_number_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_artist_disc_number_desc_idx ON s3_object_metadata(LOWER(artist), LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_artist_idx ON s3_object_metadata(LOWER(disc_number), LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_disc_number_artist_desc_idx ON s3_object_metadata(LOWER(disc_number), LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_artist_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_artist_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_disc_number_idx ON s3_object_metadata(LOWER(album), LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_album_desc_disc_number_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_album_disc_number_desc_idx ON s3_object_metadata(LOWER(album), LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_album_idx ON s3_object_metadata(LOWER(disc_number), LOWER(album), object_key);
CREATE INDEX s3_object_metadata_disc_number_album_desc_idx ON s3_object_metadata(LOWER(disc_number), LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_album_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_album_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_disc_number_idx ON s3_object_metadata(date, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_date_desc_disc_number_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_date_disc_number_desc_idx ON s3_object_metadata(date, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_disc_number_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_date_idx ON s3_object_metadata(LOWER(disc_number), date, object_key);
CREATE INDEX s3_object_metadata_disc_number_date_desc_idx ON s3_object_metadata(LOWER(disc_number), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_date_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_date_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_disc_number_idx ON s3_object_metadata(duration, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_duration_desc_disc_number_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_duration_disc_number_desc_idx ON s3_object_metadata(duration, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_disc_number_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_duration_idx ON s3_object_metadata(LOWER(disc_number), duration, object_key);
CREATE INDEX s3_object_metadata_disc_number_duration_desc_idx ON s3_object_metadata(LOWER(disc_number), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_duration_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_duration_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_disc_number_idx ON s3_object_metadata(LOWER(track_number), LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_disc_number_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_track_number_disc_number_desc_idx ON s3_object_metadata(LOWER(track_number), LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_track_number_idx ON s3_object_metadata(LOWER(disc_number), LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_disc_number_track_number_desc_idx ON s3_object_metadata(LOWER(disc_number), LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_track_number_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_track_number_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_disc_number_width_idx ON s3_object_metadata(LOWER(disc_number), width, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_width_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_disc_number_width_desc_idx ON s3_object_metadata(LOWER(disc_number), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_width_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_disc_number_idx ON s3_object_metadata(width, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_width_disc_number_desc_idx ON s3_object_metadata(width, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_disc_number_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_width_desc_disc_number_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_disc_number_height_idx ON s3_object_metadata(LOWER(disc_number), height, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_height_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_disc_number_height_desc_idx ON s3_object_metadata(LOWER(disc_number), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_height_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_disc_number_idx ON s3_object_metadata(height, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_height_disc_number_desc_idx ON s3_object_metadata(height, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_disc_number_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_height_desc_disc_number_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_disc_number_size_idx ON s3_object_metadata(LOWER(disc_number), size, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_size_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_disc_number_size_desc_idx ON s3_object_metadata(LOWER(disc_number), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_size_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_disc_number_idx ON s3_object_metadata(size, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_size_disc_number_desc_idx ON s3_object_metadata(size, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_disc_number_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_size_desc_disc_number_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
