ALTER TABLE post_edit_history DROP CONSTRAINT post_edit_history_fk_post_fkey;
ALTER TABLE post_edit_history ADD CONSTRAINT post_edit_history_fk_post_fkey FOREIGN KEY (fk_post) REFERENCES post(pk);

ALTER TABLE post_edit_history_tag DROP CONSTRAINT post_edit_history_tag_fk_post_edit_history_fkey;
ALTER TABLE post_edit_history_tag ADD CONSTRAINT post_edit_history_tag_fk_post_edit_history_fkey FOREIGN KEY (fk_post_edit_history) REFERENCES post_edit_history(pk);
ALTER TABLE post_edit_history_tag DROP CONSTRAINT post_edit_history_tag_fk_tag_fkey;
ALTER TABLE post_edit_history_tag ADD CONSTRAINT post_edit_history_tag_fk_tag_fkey FOREIGN KEY (fk_tag) REFERENCES tag(pk);

ALTER TABLE post_edit_history_group_access DROP CONSTRAINT post_edit_history_group_access_fk_post_edit_history_fkey;
ALTER TABLE post_edit_history_group_access ADD CONSTRAINT post_edit_history_group_access_fk_post_edit_history_fkey FOREIGN KEY (fk_post_edit_history) REFERENCES post_edit_history(pk);
ALTER TABLE post_edit_history_group_access DROP CONSTRAINT post_edit_history_group_access_fk_granted_group_fkey;
ALTER TABLE post_edit_history_group_access ADD CONSTRAINT post_edit_history_group_access_fk_granted_group_fkey FOREIGN KEY (fk_granted_group) REFERENCES user_group(pk);

ALTER TABLE post_collection_edit_history DROP CONSTRAINT post_collection_edit_history_fk_post_collection_fkey;
ALTER TABLE post_collection_edit_history ADD CONSTRAINT post_collection_edit_history_fk_post_collection_fkey FOREIGN KEY (fk_post_collection) REFERENCES post_collection(pk);

ALTER TABLE post_collection_edit_history_tag DROP CONSTRAINT post_collection_edit_history__fk_post_collection_edit_hist_fkey;
ALTER TABLE post_collection_edit_history_tag ADD CONSTRAINT post_collection_edit_history__fk_post_collection_edit_hist_fkey FOREIGN KEY (fk_post_collection_edit_history) REFERENCES post_collection_edit_history(pk);
ALTER TABLE post_collection_edit_history_tag DROP CONSTRAINT post_collection_edit_history_tag_fk_tag_fkey;
ALTER TABLE post_collection_edit_history_tag ADD CONSTRAINT post_collection_edit_history_tag_fk_tag_fkey FOREIGN KEY (fk_tag) REFERENCES tag(pk);

ALTER TABLE post_collection_edit_history_group_access DROP CONSTRAINT post_collection_edit_history_fk_post_collection_edit_hist_fkey1;
ALTER TABLE post_collection_edit_history_group_access ADD CONSTRAINT post_collection_edit_history_fk_post_collection_edit_hist_fkey1 FOREIGN KEY (fk_post_collection_edit_history) REFERENCES post_collection_edit_history(pk);
ALTER TABLE post_collection_edit_history_group_access DROP CONSTRAINT post_collection_edit_history_group_access_fk_granted_group_fkey;
ALTER TABLE post_collection_edit_history_group_access ADD CONSTRAINT post_collection_edit_history_group_access_fk_granted_group_fkey FOREIGN KEY (fk_granted_group) REFERENCES user_group(pk);
