ALTER TABLE post ALTER COLUMN s3_object SET NOT NULL;

ALTER TABLE s3_object_metadata ALTER COLUMN date TYPE timestamp with time zone USING nullif(regexp_replace(date, '(\d+):(\d+):(\d+) (\d+):(\d+)(:\d+)?(\+\d+:\d+)?', '\1-\2-\3 \4:\5\6\7'), '0000-00-00 00:00:00')::timestamp;
ALTER TABLE s3_object_metadata ALTER COLUMN duration TYPE interval USING duration::interval;
ALTER TABLE s3_object_metadata ADD COLUMN loaded BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE s3_object_metadata SET loaded = true WHERE raw != '{}';

INSERT INTO s3_object_metadata(object_key, raw) SELECT object_key, '{}' FROM s3_object WHERE NOT EXISTS (SELECT * FROM s3_object_metadata WHERE s3_object_metadata.object_key = s3_object.object_key);

CREATE FUNCTION create_initial_s3_object_metadata() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO s3_object_metadata(object_key, loaded, raw) VALUES(NEW.object_key, false, '{}');
    RETURN NULL;
END;
$BODY$
language plpgsql;

CREATE TRIGGER create_initial_s3_object_metadata AFTER INSERT ON s3_object
FOR EACH ROW
EXECUTE PROCEDURE create_initial_s3_object_metadata();

CREATE INDEX s3_object_metadata_mime_type_idx ON s3_object_metadata(LOWER(mime_type));
CREATE INDEX s3_object_metadata_mime_type_gin_idx ON s3_object_metadata USING gin(LOWER(mime_type) gin_trgm_ops);

CREATE INDEX s3_object_metadata_artist_idx ON s3_object_metadata(LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_artist_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_gin_idx ON s3_object_metadata USING gin(LOWER(artist) gin_trgm_ops);

CREATE INDEX s3_object_metadata_album_idx ON s3_object_metadata(LOWER(album), object_key);
CREATE INDEX s3_object_metadata_album_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_gin_idx ON s3_object_metadata USING gin(LOWER(album) gin_trgm_ops);

CREATE INDEX s3_object_metadata_artist_album_idx ON s3_object_metadata(LOWER(artist), LOWER(album), object_key);
CREATE INDEX s3_object_metadata_artist_desc_album_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_artist_album_desc_idx ON s3_object_metadata(LOWER(artist), LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_album_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_artist_idx ON s3_object_metadata(LOWER(album), LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_album_artist_desc_idx ON s3_object_metadata(LOWER(album), LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_artist_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_album_desc_artist_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_genre_idx ON s3_object_metadata(LOWER(genre));
CREATE INDEX s3_object_metadata_genre_gin_idx ON s3_object_metadata USING gin(LOWER(genre) gin_trgm_ops);

CREATE INDEX s3_object_metadata_date_idx ON s3_object_metadata(date, object_key);
CREATE INDEX s3_object_metadata_date_desc_idx ON s3_object_metadata(date DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_artist_date_idx ON s3_object_metadata(LOWER(artist), date, object_key);
CREATE INDEX s3_object_metadata_artist_desc_date_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_artist_date_desc_idx ON s3_object_metadata(LOWER(artist), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_date_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_artist_idx ON s3_object_metadata(date, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_date_artist_desc_idx ON s3_object_metadata(date, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_artist_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_date_desc_artist_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_date_idx ON s3_object_metadata(LOWER(album), date, object_key);
CREATE INDEX s3_object_metadata_album_desc_date_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_album_date_desc_idx ON s3_object_metadata(LOWER(album), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_date_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_album_idx ON s3_object_metadata(date, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_date_album_desc_idx ON s3_object_metadata(date, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_album_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_date_desc_album_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_duration_idx ON s3_object_metadata(duration, object_key);
CREATE INDEX s3_object_metadata_duration_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_artist_duration_idx ON s3_object_metadata(LOWER(artist), duration, object_key);
CREATE INDEX s3_object_metadata_artist_desc_duration_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_artist_duration_desc_idx ON s3_object_metadata(LOWER(artist), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_duration_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_artist_idx ON s3_object_metadata(duration, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_duration_artist_desc_idx ON s3_object_metadata(duration, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_artist_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_duration_desc_artist_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_duration_idx ON s3_object_metadata(LOWER(album), duration, object_key);
CREATE INDEX s3_object_metadata_album_desc_duration_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_album_duration_desc_idx ON s3_object_metadata(LOWER(album), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_duration_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_album_idx ON s3_object_metadata(duration, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_duration_album_desc_idx ON s3_object_metadata(duration, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_album_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_duration_desc_album_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_duration_idx ON s3_object_metadata(date, duration, object_key);
CREATE INDEX s3_object_metadata_date_desc_duration_idx ON s3_object_metadata(date DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_date_duration_desc_idx ON s3_object_metadata(date, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_duration_desc_idx ON s3_object_metadata(date DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_date_idx ON s3_object_metadata(duration, date, object_key);
CREATE INDEX s3_object_metadata_duration_date_desc_idx ON s3_object_metadata(duration, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_date_idx ON s3_object_metadata(duration DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_duration_desc_date_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, date DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_track_number_idx ON s3_object_metadata(LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_gin_idx ON s3_object_metadata USING gin(LOWER(track_number) gin_trgm_ops);

CREATE INDEX s3_object_metadata_artist_track_number_idx ON s3_object_metadata(LOWER(artist), LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_artist_desc_track_number_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_artist_track_number_desc_idx ON s3_object_metadata(LOWER(artist), LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_track_number_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_artist_idx ON s3_object_metadata(LOWER(track_number), LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_track_number_artist_desc_idx ON s3_object_metadata(LOWER(track_number), LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_artist_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_artist_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_track_number_idx ON s3_object_metadata(LOWER(album), LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_album_desc_track_number_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_album_track_number_desc_idx ON s3_object_metadata(LOWER(album), LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_track_number_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_album_idx ON s3_object_metadata(LOWER(track_number), LOWER(album), object_key);
CREATE INDEX s3_object_metadata_track_number_album_desc_idx ON s3_object_metadata(LOWER(track_number), LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_album_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_album_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_track_number_idx ON s3_object_metadata(date, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_date_desc_track_number_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_date_track_number_desc_idx ON s3_object_metadata(date, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_track_number_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_date_idx ON s3_object_metadata(LOWER(track_number), date, object_key);
CREATE INDEX s3_object_metadata_track_number_date_desc_idx ON s3_object_metadata(LOWER(track_number), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_date_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_date_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_track_number_idx ON s3_object_metadata(duration, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_duration_desc_track_number_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_duration_track_number_desc_idx ON s3_object_metadata(duration, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_track_number_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_duration_idx ON s3_object_metadata(LOWER(track_number), duration, object_key);
CREATE INDEX s3_object_metadata_track_number_duration_desc_idx ON s3_object_metadata(LOWER(track_number), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_duration_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_duration_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, duration DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_disc_number_idx ON s3_object_metadata(LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_gin_idx ON s3_object_metadata USING gin(LOWER(disc_number) gin_trgm_ops);

CREATE INDEX s3_object_metadata_artist_disc_number_idx ON s3_object_metadata(LOWER(artist), LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_artist_desc_disc_number_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_artist_disc_number_desc_idx ON s3_object_metadata(LOWER(artist), LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_artist_idx ON s3_object_metadata(LOWER(disc_number), LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_disc_number_artist_desc_idx ON s3_object_metadata(LOWER(disc_number), LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_artist_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_artist_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_disc_number_idx ON s3_object_metadata(LOWER(album), LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_album_desc_disc_number_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_album_disc_number_desc_idx ON s3_object_metadata(LOWER(album), LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_album_idx ON s3_object_metadata(LOWER(disc_number), LOWER(album), object_key);
CREATE INDEX s3_object_metadata_disc_number_album_desc_idx ON s3_object_metadata(LOWER(disc_number), LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_album_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_album_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_disc_number_idx ON s3_object_metadata(date, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_date_desc_disc_number_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_date_disc_number_desc_idx ON s3_object_metadata(date, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_disc_number_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_date_idx ON s3_object_metadata(LOWER(disc_number), date, object_key);
CREATE INDEX s3_object_metadata_disc_number_date_desc_idx ON s3_object_metadata(LOWER(disc_number), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_date_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_date_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_disc_number_idx ON s3_object_metadata(duration, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_duration_desc_disc_number_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_duration_disc_number_desc_idx ON s3_object_metadata(duration, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_disc_number_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_duration_idx ON s3_object_metadata(LOWER(disc_number), duration, object_key);
CREATE INDEX s3_object_metadata_disc_number_duration_desc_idx ON s3_object_metadata(LOWER(disc_number), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_duration_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_duration_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_disc_number_idx ON s3_object_metadata(LOWER(track_number), LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_disc_number_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_track_number_disc_number_desc_idx ON s3_object_metadata(LOWER(track_number), LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_track_number_idx ON s3_object_metadata(LOWER(disc_number), LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_disc_number_track_number_desc_idx ON s3_object_metadata(LOWER(disc_number), LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_track_number_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_track_number_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_width_idx ON s3_object_metadata(width, object_key);
CREATE INDEX s3_object_metadata_width_desc_idx ON s3_object_metadata(width DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_artist_width_idx ON s3_object_metadata(LOWER(artist), width, object_key);
CREATE INDEX s3_object_metadata_artist_desc_width_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_artist_width_desc_idx ON s3_object_metadata(LOWER(artist), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_width_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_artist_idx ON s3_object_metadata(width, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_width_artist_desc_idx ON s3_object_metadata(width, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_artist_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_width_desc_artist_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_width_idx ON s3_object_metadata(LOWER(album), width, object_key);
CREATE INDEX s3_object_metadata_album_desc_width_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_album_width_desc_idx ON s3_object_metadata(LOWER(album), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_width_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_album_idx ON s3_object_metadata(width, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_width_album_desc_idx ON s3_object_metadata(width, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_album_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_width_desc_album_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_width_idx ON s3_object_metadata(date, width, object_key);
CREATE INDEX s3_object_metadata_date_desc_width_idx ON s3_object_metadata(date DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_date_width_desc_idx ON s3_object_metadata(date, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_width_desc_idx ON s3_object_metadata(date DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_date_idx ON s3_object_metadata(width, date, object_key);
CREATE INDEX s3_object_metadata_width_date_desc_idx ON s3_object_metadata(width, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_date_idx ON s3_object_metadata(width DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_width_desc_date_desc_idx ON s3_object_metadata(width DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_width_idx ON s3_object_metadata(duration, width, object_key);
CREATE INDEX s3_object_metadata_duration_desc_width_idx ON s3_object_metadata(duration DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_duration_width_desc_idx ON s3_object_metadata(duration, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_width_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_duration_idx ON s3_object_metadata(width, duration, object_key);
CREATE INDEX s3_object_metadata_width_duration_desc_idx ON s3_object_metadata(width, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_duration_idx ON s3_object_metadata(width DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_width_desc_duration_desc_idx ON s3_object_metadata(width DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_width_idx ON s3_object_metadata(LOWER(track_number), width, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_width_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_track_number_width_desc_idx ON s3_object_metadata(LOWER(track_number), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_width_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_track_number_idx ON s3_object_metadata(width, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_width_track_number_desc_idx ON s3_object_metadata(width, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_track_number_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_width_desc_track_number_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_width_idx ON s3_object_metadata(LOWER(disc_number), width, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_width_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_disc_number_width_desc_idx ON s3_object_metadata(LOWER(disc_number), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_width_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_disc_number_idx ON s3_object_metadata(width, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_width_disc_number_desc_idx ON s3_object_metadata(width, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_disc_number_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_width_desc_disc_number_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_height_idx ON s3_object_metadata(height, object_key);
CREATE INDEX s3_object_metadata_height_desc_idx ON s3_object_metadata(height DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_artist_height_idx ON s3_object_metadata(LOWER(artist), height, object_key);
CREATE INDEX s3_object_metadata_artist_desc_height_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_artist_height_desc_idx ON s3_object_metadata(LOWER(artist), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_height_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_artist_idx ON s3_object_metadata(height, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_height_artist_desc_idx ON s3_object_metadata(height, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_artist_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_height_desc_artist_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_height_idx ON s3_object_metadata(LOWER(album), height, object_key);
CREATE INDEX s3_object_metadata_album_desc_height_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_album_height_desc_idx ON s3_object_metadata(LOWER(album), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_height_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_album_idx ON s3_object_metadata(height, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_height_album_desc_idx ON s3_object_metadata(height, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_album_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_height_desc_album_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_height_idx ON s3_object_metadata(date, height, object_key);
CREATE INDEX s3_object_metadata_date_desc_height_idx ON s3_object_metadata(date DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_date_height_desc_idx ON s3_object_metadata(date, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_height_desc_idx ON s3_object_metadata(date DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_date_idx ON s3_object_metadata(height, date, object_key);
CREATE INDEX s3_object_metadata_height_date_desc_idx ON s3_object_metadata(height, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_date_idx ON s3_object_metadata(height DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_height_desc_date_desc_idx ON s3_object_metadata(height DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_height_idx ON s3_object_metadata(duration, height, object_key);
CREATE INDEX s3_object_metadata_duration_desc_height_idx ON s3_object_metadata(duration DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_duration_height_desc_idx ON s3_object_metadata(duration, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_height_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_duration_idx ON s3_object_metadata(height, duration, object_key);
CREATE INDEX s3_object_metadata_height_duration_desc_idx ON s3_object_metadata(height, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_duration_idx ON s3_object_metadata(height DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_height_desc_duration_desc_idx ON s3_object_metadata(height DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_height_idx ON s3_object_metadata(LOWER(track_number), height, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_height_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_track_number_height_desc_idx ON s3_object_metadata(LOWER(track_number), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_height_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_track_number_idx ON s3_object_metadata(height, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_height_track_number_desc_idx ON s3_object_metadata(height, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_track_number_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_height_desc_track_number_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_height_idx ON s3_object_metadata(LOWER(disc_number), height, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_height_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_disc_number_height_desc_idx ON s3_object_metadata(LOWER(disc_number), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_height_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_disc_number_idx ON s3_object_metadata(height, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_height_disc_number_desc_idx ON s3_object_metadata(height, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_disc_number_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_height_desc_disc_number_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_height_idx ON s3_object_metadata(width, height, object_key);
CREATE INDEX s3_object_metadata_width_desc_height_idx ON s3_object_metadata(width DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_width_height_desc_idx ON s3_object_metadata(width, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_height_desc_idx ON s3_object_metadata(width DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_width_idx ON s3_object_metadata(height, width, object_key);
CREATE INDEX s3_object_metadata_height_width_desc_idx ON s3_object_metadata(height, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_width_idx ON s3_object_metadata(height DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_height_desc_width_desc_idx ON s3_object_metadata(height DESC NULLS LAST, width DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_size_idx ON s3_object_metadata(size, object_key);
CREATE INDEX s3_object_metadata_size_desc_idx ON s3_object_metadata(size DESC NULLS LAST, object_key);

CREATE INDEX s3_object_metadata_artist_size_idx ON s3_object_metadata(LOWER(artist), size, object_key);
CREATE INDEX s3_object_metadata_artist_desc_size_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_artist_size_desc_idx ON s3_object_metadata(LOWER(artist), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_size_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_artist_idx ON s3_object_metadata(size, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_size_artist_desc_idx ON s3_object_metadata(size, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_artist_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_size_desc_artist_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_size_idx ON s3_object_metadata(LOWER(album), size, object_key);
CREATE INDEX s3_object_metadata_album_desc_size_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_album_size_desc_idx ON s3_object_metadata(LOWER(album), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_size_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_album_idx ON s3_object_metadata(size, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_size_album_desc_idx ON s3_object_metadata(size, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_album_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_size_desc_album_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_size_idx ON s3_object_metadata(date, size, object_key);
CREATE INDEX s3_object_metadata_date_desc_size_idx ON s3_object_metadata(date DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_date_size_desc_idx ON s3_object_metadata(date, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_size_desc_idx ON s3_object_metadata(date DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_date_idx ON s3_object_metadata(size, date, object_key);
CREATE INDEX s3_object_metadata_size_date_desc_idx ON s3_object_metadata(size, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_date_idx ON s3_object_metadata(size DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_size_desc_date_desc_idx ON s3_object_metadata(size DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_size_idx ON s3_object_metadata(duration, size, object_key);
CREATE INDEX s3_object_metadata_duration_desc_size_idx ON s3_object_metadata(duration DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_duration_size_desc_idx ON s3_object_metadata(duration, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_size_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_duration_idx ON s3_object_metadata(size, duration, object_key);
CREATE INDEX s3_object_metadata_size_duration_desc_idx ON s3_object_metadata(size, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_duration_idx ON s3_object_metadata(size DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_size_desc_duration_desc_idx ON s3_object_metadata(size DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_size_idx ON s3_object_metadata(LOWER(track_number), size, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_size_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_track_number_size_desc_idx ON s3_object_metadata(LOWER(track_number), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_size_desc_idx ON s3_object_metadata(LOWER(track_number) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_track_number_idx ON s3_object_metadata(size, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_size_track_number_desc_idx ON s3_object_metadata(size, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_track_number_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(track_number), object_key);
CREATE INDEX s3_object_metadata_size_desc_track_number_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(track_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_size_idx ON s3_object_metadata(LOWER(disc_number), size, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_size_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_disc_number_size_desc_idx ON s3_object_metadata(LOWER(disc_number), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_size_desc_idx ON s3_object_metadata(LOWER(disc_number) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_disc_number_idx ON s3_object_metadata(size, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_size_disc_number_desc_idx ON s3_object_metadata(size, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_disc_number_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(disc_number), object_key);
CREATE INDEX s3_object_metadata_size_desc_disc_number_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(disc_number) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_size_idx ON s3_object_metadata(width, size, object_key);
CREATE INDEX s3_object_metadata_width_desc_size_idx ON s3_object_metadata(width DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_width_size_desc_idx ON s3_object_metadata(width, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_size_desc_idx ON s3_object_metadata(width DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_width_idx ON s3_object_metadata(size, width, object_key);
CREATE INDEX s3_object_metadata_size_width_desc_idx ON s3_object_metadata(size, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_width_idx ON s3_object_metadata(size DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_size_desc_width_desc_idx ON s3_object_metadata(size DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_size_idx ON s3_object_metadata(height, size, object_key);
CREATE INDEX s3_object_metadata_height_desc_size_idx ON s3_object_metadata(height DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_height_size_desc_idx ON s3_object_metadata(height, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_size_desc_idx ON s3_object_metadata(height DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_height_idx ON s3_object_metadata(size, height, object_key);
CREATE INDEX s3_object_metadata_size_height_desc_idx ON s3_object_metadata(size, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_height_idx ON s3_object_metadata(size DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_size_desc_height_desc_idx ON s3_object_metadata(size DESC NULLS LAST, height DESC NULLS LAST, object_key);
