DROP TRIGGER set_empty_s3_object_metadata_strings_to_null ON s3_object_metadata;
DROP FUNCTION set_empty_s3_object_metadata_strings_to_null();

DROP INDEX s3_object_metadata_video_idx;
DROP INDEX s3_object_metadata_audio_idx;
DROP INDEX s3_object_metadata_image_idx;

-- Remove semantic ordering override indexes.
DROP INDEX s3_object_metadata_artist_ordering_idx;
DROP INDEX s3_object_metadata_artist_desc_ordering_idx;
DROP INDEX s3_object_metadata_album_ordering_idx;
DROP INDEX s3_object_metadata_album_desc_ordering_idx;
DROP INDEX s3_object_metadata_disc_number_ordering_idx;
DROP INDEX s3_object_metadata_disc_number_desc_ordering_idx;
DROP INDEX s3_object_metadata_width_ordering_idx;
DROP INDEX s3_object_metadata_width_desc_ordering_idx;
DROP INDEX s3_object_metadata_height_ordering_idx;
DROP INDEX s3_object_metadata_height_desc_ordering_idx;

-- Restore desc variants of single-expression ordering indexes.
CREATE INDEX s3_object_metadata_artist_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_idx ON s3_object_metadata(width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_idx ON s3_object_metadata(height DESC NULLS LAST, object_key);

-- Restore s3_object_metadata combinatorial sort indexes.
CREATE INDEX s3_object_metadata_album_artist_idx ON s3_object_metadata(LOWER(album), LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_album_artist_desc_idx ON s3_object_metadata(LOWER(album), LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_artist_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_album_desc_artist_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_date_idx ON s3_object_metadata(LOWER(album), date, object_key);
CREATE INDEX s3_object_metadata_album_date_desc_idx ON s3_object_metadata(LOWER(album), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_date_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_album_desc_date_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_disc_number_idx ON s3_object_metadata(LOWER(album), disc_number, object_key);
CREATE INDEX s3_object_metadata_album_disc_number_desc_idx ON s3_object_metadata(LOWER(album), disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_disc_number_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_album_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_duration_idx ON s3_object_metadata(LOWER(album), duration, object_key);
CREATE INDEX s3_object_metadata_album_duration_desc_idx ON s3_object_metadata(LOWER(album), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_duration_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_album_desc_duration_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_height_idx ON s3_object_metadata(LOWER(album), height, object_key);
CREATE INDEX s3_object_metadata_album_height_desc_idx ON s3_object_metadata(LOWER(album), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_height_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_album_desc_height_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_size_idx ON s3_object_metadata(LOWER(album), size, object_key);
CREATE INDEX s3_object_metadata_album_size_desc_idx ON s3_object_metadata(LOWER(album), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_size_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_album_desc_size_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_track_number_idx ON s3_object_metadata(LOWER(album), track_number, object_key);
CREATE INDEX s3_object_metadata_album_track_number_desc_idx ON s3_object_metadata(LOWER(album), track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_track_number_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_album_desc_track_number_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_width_idx ON s3_object_metadata(LOWER(album), width, object_key);
CREATE INDEX s3_object_metadata_album_width_desc_idx ON s3_object_metadata(LOWER(album), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_album_desc_width_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_album_desc_width_desc_idx ON s3_object_metadata(LOWER(album) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_album_idx ON s3_object_metadata(LOWER(artist), LOWER(album), object_key);
CREATE INDEX s3_object_metadata_artist_album_desc_idx ON s3_object_metadata(LOWER(artist), LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_album_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_artist_desc_album_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_date_idx ON s3_object_metadata(LOWER(artist), date, object_key);
CREATE INDEX s3_object_metadata_artist_date_desc_idx ON s3_object_metadata(LOWER(artist), date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_date_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_artist_desc_date_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_disc_number_idx ON s3_object_metadata(LOWER(artist), disc_number, object_key);
CREATE INDEX s3_object_metadata_artist_disc_number_desc_idx ON s3_object_metadata(LOWER(artist), disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_disc_number_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_artist_desc_disc_number_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_duration_idx ON s3_object_metadata(LOWER(artist), duration, object_key);
CREATE INDEX s3_object_metadata_artist_duration_desc_idx ON s3_object_metadata(LOWER(artist), duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_duration_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_artist_desc_duration_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_height_idx ON s3_object_metadata(LOWER(artist), height, object_key);
CREATE INDEX s3_object_metadata_artist_height_desc_idx ON s3_object_metadata(LOWER(artist), height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_height_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_artist_desc_height_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_size_idx ON s3_object_metadata(LOWER(artist), size, object_key);
CREATE INDEX s3_object_metadata_artist_size_desc_idx ON s3_object_metadata(LOWER(artist), size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_size_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_artist_desc_size_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_track_number_idx ON s3_object_metadata(LOWER(artist), track_number, object_key);
CREATE INDEX s3_object_metadata_artist_track_number_desc_idx ON s3_object_metadata(LOWER(artist), track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_track_number_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_artist_desc_track_number_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_width_idx ON s3_object_metadata(LOWER(artist), width, object_key);
CREATE INDEX s3_object_metadata_artist_width_desc_idx ON s3_object_metadata(LOWER(artist), width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_artist_desc_width_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_artist_desc_width_desc_idx ON s3_object_metadata(LOWER(artist) DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_album_idx ON s3_object_metadata(date, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_date_album_desc_idx ON s3_object_metadata(date, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_album_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_date_desc_album_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_artist_idx ON s3_object_metadata(date, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_date_artist_desc_idx ON s3_object_metadata(date, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_artist_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_date_desc_artist_desc_idx ON s3_object_metadata(date DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_disc_number_idx ON s3_object_metadata(date, disc_number, object_key);
CREATE INDEX s3_object_metadata_date_disc_number_desc_idx ON s3_object_metadata(date, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_disc_number_idx ON s3_object_metadata(date DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_date_desc_disc_number_desc_idx ON s3_object_metadata(date DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_duration_idx ON s3_object_metadata(date, duration, object_key);
CREATE INDEX s3_object_metadata_date_duration_desc_idx ON s3_object_metadata(date, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_duration_idx ON s3_object_metadata(date DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_date_desc_duration_desc_idx ON s3_object_metadata(date DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_height_idx ON s3_object_metadata(date, height, object_key);
CREATE INDEX s3_object_metadata_date_height_desc_idx ON s3_object_metadata(date, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_height_idx ON s3_object_metadata(date DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_date_desc_height_desc_idx ON s3_object_metadata(date DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_size_idx ON s3_object_metadata(date, size, object_key);
CREATE INDEX s3_object_metadata_date_size_desc_idx ON s3_object_metadata(date, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_size_idx ON s3_object_metadata(date DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_date_desc_size_desc_idx ON s3_object_metadata(date DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_track_number_idx ON s3_object_metadata(date, track_number, object_key);
CREATE INDEX s3_object_metadata_date_track_number_desc_idx ON s3_object_metadata(date, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_track_number_idx ON s3_object_metadata(date DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_date_desc_track_number_desc_idx ON s3_object_metadata(date DESC NULLS LAST, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_width_idx ON s3_object_metadata(date, width, object_key);
CREATE INDEX s3_object_metadata_date_width_desc_idx ON s3_object_metadata(date, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_date_desc_width_idx ON s3_object_metadata(date DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_date_desc_width_desc_idx ON s3_object_metadata(date DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_album_idx ON s3_object_metadata(disc_number, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_disc_number_album_desc_idx ON s3_object_metadata(disc_number, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_album_idx ON s3_object_metadata(disc_number DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_album_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_artist_idx ON s3_object_metadata(disc_number, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_disc_number_artist_desc_idx ON s3_object_metadata(disc_number, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_artist_idx ON s3_object_metadata(disc_number DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_artist_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_date_idx ON s3_object_metadata(disc_number, date, object_key);
CREATE INDEX s3_object_metadata_disc_number_date_desc_idx ON s3_object_metadata(disc_number, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_date_idx ON s3_object_metadata(disc_number DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_date_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_duration_idx ON s3_object_metadata(disc_number, duration, object_key);
CREATE INDEX s3_object_metadata_disc_number_duration_desc_idx ON s3_object_metadata(disc_number, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_duration_idx ON s3_object_metadata(disc_number DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_duration_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_height_idx ON s3_object_metadata(disc_number, height, object_key);
CREATE INDEX s3_object_metadata_disc_number_height_desc_idx ON s3_object_metadata(disc_number, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_height_idx ON s3_object_metadata(disc_number DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_height_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_size_idx ON s3_object_metadata(disc_number, size, object_key);
CREATE INDEX s3_object_metadata_disc_number_size_desc_idx ON s3_object_metadata(disc_number, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_size_idx ON s3_object_metadata(disc_number DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_size_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_track_number_idx ON s3_object_metadata(disc_number, track_number, object_key);
CREATE INDEX s3_object_metadata_disc_number_track_number_desc_idx ON s3_object_metadata(disc_number, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_track_number_idx ON s3_object_metadata(disc_number DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_track_number_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_width_idx ON s3_object_metadata(disc_number, width, object_key);
CREATE INDEX s3_object_metadata_disc_number_width_desc_idx ON s3_object_metadata(disc_number, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_width_idx ON s3_object_metadata(disc_number DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_disc_number_desc_width_desc_idx ON s3_object_metadata(disc_number DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_album_idx ON s3_object_metadata(duration, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_duration_album_desc_idx ON s3_object_metadata(duration, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_album_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_duration_desc_album_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_artist_idx ON s3_object_metadata(duration, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_duration_artist_desc_idx ON s3_object_metadata(duration, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_artist_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_duration_desc_artist_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_date_idx ON s3_object_metadata(duration, date, object_key);
CREATE INDEX s3_object_metadata_duration_date_desc_idx ON s3_object_metadata(duration, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_date_idx ON s3_object_metadata(duration DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_duration_desc_date_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_disc_number_idx ON s3_object_metadata(duration, disc_number, object_key);
CREATE INDEX s3_object_metadata_duration_disc_number_desc_idx ON s3_object_metadata(duration, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_disc_number_idx ON s3_object_metadata(duration DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_duration_desc_disc_number_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_height_idx ON s3_object_metadata(duration, height, object_key);
CREATE INDEX s3_object_metadata_duration_height_desc_idx ON s3_object_metadata(duration, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_height_idx ON s3_object_metadata(duration DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_duration_desc_height_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_size_idx ON s3_object_metadata(duration, size, object_key);
CREATE INDEX s3_object_metadata_duration_size_desc_idx ON s3_object_metadata(duration, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_size_idx ON s3_object_metadata(duration DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_duration_desc_size_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_track_number_idx ON s3_object_metadata(duration, track_number, object_key);
CREATE INDEX s3_object_metadata_duration_track_number_desc_idx ON s3_object_metadata(duration, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_track_number_idx ON s3_object_metadata(duration DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_duration_desc_track_number_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_width_idx ON s3_object_metadata(duration, width, object_key);
CREATE INDEX s3_object_metadata_duration_width_desc_idx ON s3_object_metadata(duration, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_duration_desc_width_idx ON s3_object_metadata(duration DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_duration_desc_width_desc_idx ON s3_object_metadata(duration DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_album_idx ON s3_object_metadata(height, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_height_album_desc_idx ON s3_object_metadata(height, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_album_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_height_desc_album_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_artist_idx ON s3_object_metadata(height, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_height_artist_desc_idx ON s3_object_metadata(height, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_artist_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_height_desc_artist_desc_idx ON s3_object_metadata(height DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_date_idx ON s3_object_metadata(height, date, object_key);
CREATE INDEX s3_object_metadata_height_date_desc_idx ON s3_object_metadata(height, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_date_idx ON s3_object_metadata(height DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_height_desc_date_desc_idx ON s3_object_metadata(height DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_disc_number_idx ON s3_object_metadata(height, disc_number, object_key);
CREATE INDEX s3_object_metadata_height_disc_number_desc_idx ON s3_object_metadata(height, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_disc_number_idx ON s3_object_metadata(height DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_height_desc_disc_number_desc_idx ON s3_object_metadata(height DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_duration_idx ON s3_object_metadata(height, duration, object_key);
CREATE INDEX s3_object_metadata_height_duration_desc_idx ON s3_object_metadata(height, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_duration_idx ON s3_object_metadata(height DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_height_desc_duration_desc_idx ON s3_object_metadata(height DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_size_idx ON s3_object_metadata(height, size, object_key);
CREATE INDEX s3_object_metadata_height_size_desc_idx ON s3_object_metadata(height, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_size_idx ON s3_object_metadata(height DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_height_desc_size_desc_idx ON s3_object_metadata(height DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_track_number_idx ON s3_object_metadata(height, track_number, object_key);
CREATE INDEX s3_object_metadata_height_track_number_desc_idx ON s3_object_metadata(height, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_track_number_idx ON s3_object_metadata(height DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_height_desc_track_number_desc_idx ON s3_object_metadata(height DESC NULLS LAST, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_width_idx ON s3_object_metadata(height, width, object_key);
CREATE INDEX s3_object_metadata_height_width_desc_idx ON s3_object_metadata(height, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_height_desc_width_idx ON s3_object_metadata(height DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_height_desc_width_desc_idx ON s3_object_metadata(height DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_album_idx ON s3_object_metadata(size, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_size_album_desc_idx ON s3_object_metadata(size, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_album_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_size_desc_album_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_artist_idx ON s3_object_metadata(size, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_size_artist_desc_idx ON s3_object_metadata(size, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_artist_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_size_desc_artist_desc_idx ON s3_object_metadata(size DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_date_idx ON s3_object_metadata(size, date, object_key);
CREATE INDEX s3_object_metadata_size_date_desc_idx ON s3_object_metadata(size, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_date_idx ON s3_object_metadata(size DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_size_desc_date_desc_idx ON s3_object_metadata(size DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_disc_number_idx ON s3_object_metadata(size, disc_number, object_key);
CREATE INDEX s3_object_metadata_size_disc_number_desc_idx ON s3_object_metadata(size, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_disc_number_idx ON s3_object_metadata(size DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_size_desc_disc_number_desc_idx ON s3_object_metadata(size DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_duration_idx ON s3_object_metadata(size, duration, object_key);
CREATE INDEX s3_object_metadata_size_duration_desc_idx ON s3_object_metadata(size, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_duration_idx ON s3_object_metadata(size DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_size_desc_duration_desc_idx ON s3_object_metadata(size DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_height_idx ON s3_object_metadata(size, height, object_key);
CREATE INDEX s3_object_metadata_size_height_desc_idx ON s3_object_metadata(size, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_height_idx ON s3_object_metadata(size DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_size_desc_height_desc_idx ON s3_object_metadata(size DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_track_number_idx ON s3_object_metadata(size, track_number, object_key);
CREATE INDEX s3_object_metadata_size_track_number_desc_idx ON s3_object_metadata(size, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_track_number_idx ON s3_object_metadata(size DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_size_desc_track_number_desc_idx ON s3_object_metadata(size DESC NULLS LAST, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_width_idx ON s3_object_metadata(size, width, object_key);
CREATE INDEX s3_object_metadata_size_width_desc_idx ON s3_object_metadata(size, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_size_desc_width_idx ON s3_object_metadata(size DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_size_desc_width_desc_idx ON s3_object_metadata(size DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_album_idx ON s3_object_metadata(track_number, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_track_number_album_desc_idx ON s3_object_metadata(track_number, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_album_idx ON s3_object_metadata(track_number DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_album_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_artist_idx ON s3_object_metadata(track_number, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_track_number_artist_desc_idx ON s3_object_metadata(track_number, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_artist_idx ON s3_object_metadata(track_number DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_track_number_desc_artist_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_date_idx ON s3_object_metadata(track_number, date, object_key);
CREATE INDEX s3_object_metadata_track_number_date_desc_idx ON s3_object_metadata(track_number, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_date_idx ON s3_object_metadata(track_number DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_date_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_disc_number_idx ON s3_object_metadata(track_number, disc_number, object_key);
CREATE INDEX s3_object_metadata_track_number_disc_number_desc_idx ON s3_object_metadata(track_number, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_disc_number_idx ON s3_object_metadata(track_number DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_disc_number_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_duration_idx ON s3_object_metadata(track_number, duration, object_key);
CREATE INDEX s3_object_metadata_track_number_duration_desc_idx ON s3_object_metadata(track_number, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_duration_idx ON s3_object_metadata(track_number DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_duration_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_height_idx ON s3_object_metadata(track_number, height, object_key);
CREATE INDEX s3_object_metadata_track_number_height_desc_idx ON s3_object_metadata(track_number, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_height_idx ON s3_object_metadata(track_number DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_height_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_size_idx ON s3_object_metadata(track_number, size, object_key);
CREATE INDEX s3_object_metadata_track_number_size_desc_idx ON s3_object_metadata(track_number, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_size_idx ON s3_object_metadata(track_number DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_size_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_width_idx ON s3_object_metadata(track_number, width, object_key);
CREATE INDEX s3_object_metadata_track_number_width_desc_idx ON s3_object_metadata(track_number, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_width_idx ON s3_object_metadata(track_number DESC NULLS LAST, width, object_key);
CREATE INDEX s3_object_metadata_track_number_desc_width_desc_idx ON s3_object_metadata(track_number DESC NULLS LAST, width DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_album_idx ON s3_object_metadata(width, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_width_album_desc_idx ON s3_object_metadata(width, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_album_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(album), object_key);
CREATE INDEX s3_object_metadata_width_desc_album_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(album) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_artist_idx ON s3_object_metadata(width, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_width_artist_desc_idx ON s3_object_metadata(width, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_artist_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(artist), object_key);
CREATE INDEX s3_object_metadata_width_desc_artist_desc_idx ON s3_object_metadata(width DESC NULLS LAST, LOWER(artist) DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_date_idx ON s3_object_metadata(width, date, object_key);
CREATE INDEX s3_object_metadata_width_date_desc_idx ON s3_object_metadata(width, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_date_idx ON s3_object_metadata(width DESC NULLS LAST, date, object_key);
CREATE INDEX s3_object_metadata_width_desc_date_desc_idx ON s3_object_metadata(width DESC NULLS LAST, date DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_disc_number_idx ON s3_object_metadata(width, disc_number, object_key);
CREATE INDEX s3_object_metadata_width_disc_number_desc_idx ON s3_object_metadata(width, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_disc_number_idx ON s3_object_metadata(width DESC NULLS LAST, disc_number, object_key);
CREATE INDEX s3_object_metadata_width_desc_disc_number_desc_idx ON s3_object_metadata(width DESC NULLS LAST, disc_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_duration_idx ON s3_object_metadata(width, duration, object_key);
CREATE INDEX s3_object_metadata_width_duration_desc_idx ON s3_object_metadata(width, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_duration_idx ON s3_object_metadata(width DESC NULLS LAST, duration, object_key);
CREATE INDEX s3_object_metadata_width_desc_duration_desc_idx ON s3_object_metadata(width DESC NULLS LAST, duration DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_height_idx ON s3_object_metadata(width, height, object_key);
CREATE INDEX s3_object_metadata_width_height_desc_idx ON s3_object_metadata(width, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_height_idx ON s3_object_metadata(width DESC NULLS LAST, height, object_key);
CREATE INDEX s3_object_metadata_width_desc_height_desc_idx ON s3_object_metadata(width DESC NULLS LAST, height DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_size_idx ON s3_object_metadata(width, size, object_key);
CREATE INDEX s3_object_metadata_width_size_desc_idx ON s3_object_metadata(width, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_size_idx ON s3_object_metadata(width DESC NULLS LAST, size, object_key);
CREATE INDEX s3_object_metadata_width_desc_size_desc_idx ON s3_object_metadata(width DESC NULLS LAST, size DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_track_number_idx ON s3_object_metadata(width, track_number, object_key);
CREATE INDEX s3_object_metadata_width_track_number_desc_idx ON s3_object_metadata(width, track_number DESC NULLS LAST, object_key);
CREATE INDEX s3_object_metadata_width_desc_track_number_idx ON s3_object_metadata(width DESC NULLS LAST, track_number, object_key);
CREATE INDEX s3_object_metadata_width_desc_track_number_desc_idx ON s3_object_metadata(width DESC NULLS LAST, track_number DESC NULLS LAST, object_key);

-- Restore post combinatorial sort indexes.
CREATE INDEX post_fk_create_user_creation_timestamp_idx ON post(fk_create_user, creation_timestamp, pk DESC);
CREATE INDEX post_fk_create_user_creation_timestamp_desc_idx ON post(fk_create_user, creation_timestamp DESC, pk DESC);
CREATE INDEX post_fk_create_user_desc_creation_timestamp_idx ON post(fk_create_user DESC, creation_timestamp, pk DESC);
CREATE INDEX post_fk_create_user_desc_creation_timestamp_desc_idx ON post(fk_create_user DESC, creation_timestamp DESC, pk DESC);
CREATE INDEX post_fk_create_user_title_idx ON post(fk_create_user, LOWER(title), pk DESC);
CREATE INDEX post_fk_create_user_title_desc_idx ON post(fk_create_user, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_fk_create_user_desc_title_idx ON post(fk_create_user DESC, LOWER(title), pk DESC);
CREATE INDEX post_fk_create_user_desc_title_desc_idx ON post(fk_create_user DESC, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_creation_timestamp_fk_create_user_idx ON post(creation_timestamp, fk_create_user, pk DESC);
CREATE INDEX post_creation_timestamp_fk_create_user_desc_idx ON post(creation_timestamp, fk_create_user DESC, pk DESC);
CREATE INDEX post_creation_timestamp_desc_fk_create_user_idx ON post(creation_timestamp DESC, fk_create_user, pk DESC);
CREATE INDEX post_creation_timestamp_desc_fk_create_user_desc_idx ON post(creation_timestamp DESC, fk_create_user DESC, pk DESC);
CREATE INDEX post_creation_timestamp_title_idx ON post(creation_timestamp, LOWER(title), pk DESC);
CREATE INDEX post_creation_timestamp_title_desc_idx ON post(creation_timestamp, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_creation_timestamp_desc_title_idx ON post(creation_timestamp DESC, LOWER(title), pk DESC);
CREATE INDEX post_creation_timestamp_desc_title_desc_idx ON post(creation_timestamp DESC, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_title_fk_create_user_idx ON post(LOWER(title), fk_create_user, pk DESC);
CREATE INDEX post_title_fk_create_user_desc_idx ON post(LOWER(title), fk_create_user DESC, pk DESC);
CREATE INDEX post_title_desc_fk_create_user_idx ON post(LOWER(title) DESC NULLS LAST, fk_create_user, pk DESC);
CREATE INDEX post_title_desc_fk_create_user_desc_idx ON post(LOWER(title) DESC NULLS LAST, fk_create_user DESC, pk DESC);
CREATE INDEX post_title_creation_timestamp_idx ON post(LOWER(title), creation_timestamp, pk DESC);
CREATE INDEX post_title_creation_timestamp_desc_idx ON post(LOWER(title), creation_timestamp DESC, pk DESC);
CREATE INDEX post_title_desc_creation_timestamp_idx ON post(LOWER(title) DESC NULLS LAST, creation_timestamp, pk DESC);
CREATE INDEX post_title_desc_creation_timestamp_desc_idx ON post(LOWER(title) DESC NULLS LAST, creation_timestamp DESC, pk DESC);

-- Restore post_collection uploader index and combinatorial sort indexes.
DROP INDEX post_collection_fk_create_user_idx;
CREATE INDEX post_collection_fk_create_user_idx ON post_collection(fk_create_user);
CREATE INDEX post_collection_fk_create_user_creation_timestamp_idx ON post_collection(fk_create_user, creation_timestamp, pk DESC);
CREATE INDEX post_collection_fk_create_user_creation_timestamp_desc_idx ON post_collection(fk_create_user, creation_timestamp DESC, pk DESC);
CREATE INDEX post_collection_fk_create_user_desc_creation_timestamp_idx ON post_collection(fk_create_user DESC, creation_timestamp, pk DESC);
CREATE INDEX post_collection_fk_create_user_desc_creation_timestamp_desc_idx ON post_collection(fk_create_user DESC, creation_timestamp DESC, pk DESC);
CREATE INDEX post_collection_fk_create_user_title_idx ON post_collection(fk_create_user, LOWER(title), pk DESC);
CREATE INDEX post_collection_fk_create_user_title_desc_idx ON post_collection(fk_create_user, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_collection_fk_create_user_desc_title_idx ON post_collection(fk_create_user DESC, LOWER(title), pk DESC);
CREATE INDEX post_collection_fk_create_user_desc_title_desc_idx ON post_collection(fk_create_user DESC, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_collection_creation_timestamp_fk_create_user_idx ON post_collection(creation_timestamp, fk_create_user, pk DESC);
CREATE INDEX post_collection_creation_timestamp_fk_create_user_desc_idx ON post_collection(creation_timestamp, fk_create_user DESC, pk DESC);
CREATE INDEX post_collection_creation_timestamp_desc_fk_create_user_idx ON post_collection(creation_timestamp DESC, fk_create_user, pk DESC);
CREATE INDEX post_collection_creation_timestamp_desc_fk_create_user_desc_idx ON post_collection(creation_timestamp DESC, fk_create_user DESC, pk DESC);
CREATE INDEX post_collection_creation_timestamp_title_idx ON post_collection(creation_timestamp, LOWER(title), pk DESC);
CREATE INDEX post_collection_creation_timestamp_title_desc_idx ON post_collection(creation_timestamp, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_collection_creation_timestamp_desc_title_idx ON post_collection(creation_timestamp DESC, LOWER(title), pk DESC);
CREATE INDEX post_collection_creation_timestamp_desc_title_desc_idx ON post_collection(creation_timestamp DESC, LOWER(title) DESC NULLS LAST, pk DESC);
CREATE INDEX post_collection_title_fk_create_user_idx ON post_collection(LOWER(title), fk_create_user, pk DESC);
CREATE INDEX post_collection_title_fk_create_user_desc_idx ON post_collection(LOWER(title), fk_create_user DESC, pk DESC);
CREATE INDEX post_collection_title_desc_fk_create_user_idx ON post_collection(LOWER(title) DESC NULLS LAST, fk_create_user, pk DESC);
CREATE INDEX post_collection_title_desc_fk_create_user_desc_idx ON post_collection(LOWER(title) DESC NULLS LAST, fk_create_user DESC, pk DESC);
CREATE INDEX post_collection_title_creation_timestamp_idx ON post_collection(LOWER(title), creation_timestamp, pk DESC);
CREATE INDEX post_collection_title_creation_timestamp_desc_idx ON post_collection(LOWER(title), creation_timestamp DESC, pk DESC);
CREATE INDEX post_collection_title_desc_creation_timestamp_idx ON post_collection(LOWER(title) DESC NULLS LAST, creation_timestamp, pk DESC);
CREATE INDEX post_collection_title_desc_creation_timestamp_desc_idx ON post_collection(LOWER(title) DESC NULLS LAST, creation_timestamp DESC, pk DESC);

-- Restore user_group combinatorial sort indexes.
CREATE INDEX user_group_creation_timestamp_name_idx ON user_group(creation_timestamp, LOWER(name), pk DESC);
CREATE INDEX user_group_creation_timestamp_name_desc_idx ON user_group(creation_timestamp, LOWER(name) DESC, pk DESC);
CREATE INDEX user_group_creation_timestamp_desc_name_idx ON user_group(creation_timestamp DESC, LOWER(name), pk DESC);
CREATE INDEX user_group_creation_timestamp_desc_name_desc_idx ON user_group(creation_timestamp DESC, LOWER(name) DESC, pk DESC);
CREATE INDEX user_group_name_creation_timestamp_idx ON user_group(LOWER(name), creation_timestamp, pk DESC);
CREATE INDEX user_group_name_creation_timestamp_desc_idx ON user_group(LOWER(name), creation_timestamp DESC, pk DESC);
CREATE INDEX user_group_name_desc_creation_timestamp_idx ON user_group(LOWER(name) DESC, creation_timestamp, pk DESC);
CREATE INDEX user_group_name_desc_creation_timestamp_desc_idx ON user_group(LOWER(name) DESC, creation_timestamp DESC, pk DESC);
